import Dashboard from "@/components/Dashboard";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Dashboard title='Dashboard'>
        <main>
          <h1>RFIF Card Identifier</h1>
        </main>
      </Dashboard>
    </div>
  );
}
