import Head from "next/head";
import useSWR from "swr";

import Dashboard from "@/components/Dashboard";
import { useEffect, useState } from "react";
import axios from "axios";

export default function RegisterCard() {
  const [students, setStudents] = useState([]);

  useEffect(() => {
    axios
      .get("http://localhost:3001/api/student/available")
      .then((res) => setStudents(res.data.data))
      .catch((err) => alert(err.message));
  }, []);

  //   const fetcher = (url) =>
  //     fetch(url, { headers: { devtoken } }).then((res) => res.json());
  const fetcher = (url) => fetch(url).then((res) => res.json());

  const { data, error } = useSWR(
    "http://localhost:3001/api/card/temp",
    fetcher,
    { refreshInterval: 1000 }
  );

  return (
    <>
      <Head>
        <title>Registrasi Kartu Baru</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Dashboard title='Registrasi Kartu Baru'>
        <main>
          <h3 className='mb-4 text-2xl font-normal'>Kartu aktif saat ini</h3>
          {error ? (
            <>
              <p className='text-red-500'>Terjadi kesalahan...</p>
              <p>Keterangan: {error?.message}</p>
            </>
          ) : data ? (
            <>
              <p className='text-6xl font-bold tracking-wide'>
                {data?.data?.code}
              </p>
            </>
          ) : (
            <div className='flex items-center justify-center h-24 bg-gray-200 rounded-md animate-pulse'>
              <div className='text-xl font-normal'>Loading...</div>
            </div>
          )}

          <div className='mt-8'>
            <label
              htmlFor='pairing'
              className='block text-sm font-medium text-gray-700'
            >
              Pasangkan dengan mahasiswa
            </label>
            <select
              id='pairing'
              name='pairing'
              className='block w-full py-2 pl-3 pr-10 mt-1 text-base border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm'
              defaultValue=''
            >
              <option value=''>{"Pilih Mahasiswa (NIM - Nama)"}</option>
              {students.map((student) => (
                <option
                  key={student.nim}
                >{`${student.nim} - ${student.name}`}</option>
              ))}
            </select>
          </div>
        </main>
      </Dashboard>
    </>
  );
}
