import Head from "next/head";
import useSWR from "swr";

import Dashboard from "@/components/Dashboard";
import { useEffect, useState } from "react";
import axios from "axios";

export default function RegisterCard() {
  const [students, setStudents] = useState([]);
  const [cardData, setCardData] = useState("");
  const [studentData, setStudentData] = useState(null);

  const fetcher = (url) => fetch(url).then((res) => res.json());

  const { data, error } = useSWR(
    "http://localhost:3001/api/card/get-temp",
    fetcher,
    { refreshInterval: 1000 }
  );

  useEffect(() => {
    axios
      .get("http://localhost:3001/api/student/available")
      .then((res) => setStudents(res.data.data))
      .catch((err) => alert(err.message));
  }, []);

  useEffect(() => {
    setCardData(data?.data?.code);
  }, [data]);

  const handlePairing = () => {
    if (!cardData || !studentData) {
      alert("Data can not be empty!");
      return;
    }

    const nim = studentData.split(" - ")[0];

    const data = {
      nim,
      cardId: cardData,
    };

    axios
      .post("http://localhost:3001/api/card/pair", data)
      .then((res) => alert(res?.data?.message))
      .catch((err) => alert(err?.response?.data?.message ?? "Error occurred."));
  };

  return (
    <>
      <Head>
        <title>Registrasi Kartu Baru</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Dashboard title='Registrasi Kartu Baru'>
        <main>
          <h3 className='mb-4 text-2xl font-normal'>Kartu aktif saat ini</h3>
          {error ? (
            <>
              <p className='text-red-500'>Terjadi kesalahan...</p>
              <p>Keterangan: {error?.message}</p>
            </>
          ) : data ? (
            <>
              <p className='text-6xl font-bold tracking-wide'>{cardData}</p>
            </>
          ) : (
            <div className='flex items-center justify-center h-24 bg-gray-200 rounded-md animate-pulse'>
              <div className='text-xl font-normal'>Loading...</div>
            </div>
          )}

          <div className='mt-8'>
            <label
              htmlFor='pairing'
              className='block text-sm font-medium text-gray-700'
            >
              Pasangkan dengan mahasiswa
            </label>
            <select
              id='pairing'
              name='pairing'
              className='block w-full py-2 pl-3 pr-10 mt-1 text-base border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm'
              defaultValue=''
              onChange={(e) => setStudentData(e.target.value)}
            >
              <option value=''>{"Pilih Mahasiswa (NIM - Nama)"}</option>
              {students.map((student) => (
                <option
                  key={student.nim}
                >{`${student.nim} - ${student.name}`}</option>
              ))}
            </select>
          </div>

          <button
            type='button'
            onClick={handlePairing}
            className='inline-flex items-center px-4 py-2 mt-5 text-sm font-medium text-white border border-transparent rounded-md shadow-sm bg-primary hover:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-700'
          >
            Pasangkan
          </button>
        </main>
      </Dashboard>
    </>
  );
}
